main.exe:main.o simpleSelectSort.o
	gcc -Wall -o main.o main.o simpleSelectSort.o
main.o:main.c
	gcc -Wall -o main.o -c main.c
simepleSelectSort.o:simepleSelectSort.c
	gcc -Wall -o simepleSelectSort.o -c simepleSelectSort.c

clean:
	del *.exe *.o *.obj
